dist:
  - trusty 

sudo:
  require
    
language: 
  - cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - llvm
      - lcov
      - kcov
      - cmake-data
      - binutils-dev
      - libiberty-dev
      - cmake
      - libc++-dev

script:
  - mkdir build && cd build
  - cmake -DTESTING=1 ..
  - make
  - ./tests/unit_tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - kcov --exclude-pattern=gtest,/usr out tests/unit_tests
  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"
