dist:
  - bionic 

sudo:
  require
    
language: 
  - cpp

cache: ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - llvm
      - lcov
      - kcov
      - cmake-data
      - binutils-dev
      - libiberty-dev
      - cmake
      - libc++-dev
      - libgmp3-dev
      - ccache
      - g++-5
      - gcc-5
      - g++-6
      - gcc-6
      - g++-7
      - gcc-7

matrix:
  include:
   # gcc 
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COMPILER_VERSION=5

    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COMPILER_VERSION=5

    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COMPILER_VERSION=6

    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COMPILER_VERSION=6

    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COMPILER_VERSION=7

    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COMPILER_VERSION=7

    # clang
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release 

    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug 

script:
  - export CC="${CC}-${COMPILER_VERSION}"
  - export CXX="${CXX}-${COMPILER_VERSION}"
  - ls -l /usr/lib/ccache
  # trick for using ccache, stolen from rapidcheck
  - mkdir -p ${HOME}/bin
  - export PATH="${HOME}/bin:${PATH}"
  - ln -sf /usr/bin/ccache ${HOME}/bin/"${CXX}"
  - which ${CXX}
  - which ${CC}
  # generate build files
  - cmake -H. -Bbuild -DTESTING=1 -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  # collect ccache stats
  - ccache --show-stats > ccache_before
  - cmake --build build -- -j4
  - ccache --show-stats > ccache_after
  - diff -U100 ccache_before ccache_after || true

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - kcov --exclude-pattern=expected,gtest,gmock,rapidcheck,test,mock,/usr,tests/* out tests/unit_tests
  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"

before_script:
  - wget https://soplex.zib.de/download/release/soplex-4.0.2.tgz
  - tar xzf soplex-4.0.2.tgz
  - cd soplex-4.0.2
  - cmake -H. -Bbuild
  - cmake --build build -- -j4
  - cd build && sudo make install
  - cd ${TRAVIS_BUILD_DIR}
