dist:
  - xenial

sudo:
  require
    
language: 
  - cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - llvm
      - lcov
      - kcov
      - cmake-data
      - binutils-dev
      - libiberty-dev
      - cmake
      - libc++-dev
      - libgmp3-dev

script:
  - mkdir build && cd build
  - cmake -DTESTING=1 -DCOVERAGE=1 ..
  - make
  - ./tests/unit_tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - kcov --exclude-pattern=expected,gtest,gmock,rapidcheck,test,mock,/usr out tests/unit_tests
  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"

before_script:
  - wget https://soplex.zib.de/download/release/soplex-4.0.2.tgz
  - tar xzf soplex-4.0.2.tgz
  - cd soplex-4.0.2
  - cmake -H. -Bbuild
  - cmake --build build -- -j4
  - cd build && sudo make install
  - cd ${TRAVIS_BUILD_DIR}
